### ISSUE TITLE
Can't set browser

### ISSUE THREAD

**Issue by WPettersson** [themoken/canto-curses#22]
No matter what I try, I can't seem to set the browser. I try running ':set browser firefox-bin' and ':set browser xdg-open' and it seems like canto won't recognise either. Links won't open, and when I quit and kill the daemon, my config file does not have a browser entry. I even hacked in some print()'s to the code, and it seems my settings are not recognised. Or at least, _fork() is called with "firefox" and not "firefox-bin", I can't work out where settings are actually set.

I also tried '$ canto-remote one-config CantoCurses.browser = firefox-bin %u' which does print 'CantoCurses.browser =  firefox-bin %u' but after running said command canto-curses won't start. Instead it just silently dies with 

13:40:01 : CANTO-CURSES -> Canto-curses started.
13:40:01 : CANTO-CURSES -> Exiting on exception:
13:40:01 : CANTO-CURSES -> 
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/canto_curses/main.py", line 297, in start
    self.run()
  File "/usr/lib64/python3.3/site-packages/canto_curses/main.py", line 230, in run
    self.gui = CantoCursesGui(self)
  File "/usr/lib64/python3.3/site-packages/canto_curses/gui.py", line 526, in __init__
    self.daemon_init()
  File "/usr/lib64/python3.3/site-packages/canto_curses/gui.py", line 554, in daemon_init
    self.prot_configs(self.wait_response("CONFIGS")[1])
  File "/usr/lib64/python3.3/site-packages/canto_curses/gui.py", line 918, in prot_configs
    self.validators)
  File "/usr/lib64/python3.3/site-packages/canto_curses/gui.py", line 847, in validate_config
    chgs, dels =  self.validate_config(c[key], d[key], v[key])
  File "/usr/lib64/python3.3/site-packages/canto_curses/gui.py", line 833, in validate_config
    c[key] = d[key]
TypeError: 'str' object does not support item assignment

13:40:01 : CANTO-CURSES -> Exiting.

Am I correctly setting my browser? Why won't the setting work, or even stick in the conf file?

**Comment by themoken** [comment]
What version are you running of the daemon/curses? Releases prior to 0.9.0 are deprecated, and here `:set browser` works just fine.

**Comment by WPettersson** [comment]
Aah. I'm running 0.8.2 for daemon and 0.8.4 for curses. They're the latest available in Gentoo's portage tree.
