### ISSUE TITLE
Exiting on exception (FileNotFoundError: [Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [themoken/canto-curses#53]
From curses-log:
```
08:36:17 : CANTO-CURSES -> canto-curses 0.9.9 
08:36:17 : CANTO-CURSES -> Exiting on exception:
08:36:17 : CANTO-CURSES -> 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/canto_curses/main.py", line 274, in start
    self.run()
  File "/usr/lib/python3.9/site-packages/canto_curses/main.py", line 201, in run
    if not config.init(self, CANTO_PROTOCOL_COMPATIBLE):
  File "/usr/lib/python3.9/site-packages/canto_curses/config.py", line 443, in init
    SubThread.init(self, backend)
  File "/usr/lib/python3.9/site-packages/canto_curses/subthread.py", line 23, in init
    self.conn = backend.connect()
  File "/usr/lib/python3.9/site-packages/canto_next/client.py", line 28, in connect
    conn = CantoSocket.connect(self)
  File "/usr/lib/python3.9/site-packages/canto_next/protocol.py", line 173, in connect
    sock.connect(addr)
FileNotFoundError: [Errno 2] No such file or directory

08:36:17 : CANTO-CURSES -> Exiting.
```

From daemon-log:
```
08:36:17 : CANTO-DAEMON -> canto-daemon 0.9.7 
08:36:17 : CANTO-DAEMON -> verbosity = 1
08:36:17 : CANTO-DAEMON -> conf_dir = /home/mortimer/.config/canto
08:36:17 : CONFIG -> Read /home/mortimer/.config/canto/conf
08:36:17 : CONFIG -> Parsed into: {'defaults': {'global_transform': 'filter_read', 'keep_time': 86400, 'keep_unread': False, 'rate': 10}, 'feeds': [{'name': 'Canto', 'url': 'http://codezen.org/canto-ng/feed/'}, {'name': 'Slashdot', 'url': 'http://rss.slashdot.org/slashdot/Slashdot'}, {'name': 'Reddit', 'url': 'http://reddit.com/.rss'}]}
08:36:17 : CONFIG -> Validated: {'defaults': {'global_transform': 'filter_read', 'keep_time': 86400, 'keep_unread': False, 'rate': 10}, 'feeds': [{'name': 'Canto', 'url': 'http://codezen.org/canto-ng/feed/'}, {'name': 'Slashdot', 'url': 'http://rss.slashdot.org/slashdot/Slashdot'}, {'name': 'Reddit', 'url': 'http://reddit.com/.rss'}]}
08:36:17 : CANTO-FETCH -> Thread Limit: 2
08:36:17 : CANTO-DAEMON -> Listening on unix socket: /home/mortimer/.config/canto/.canto_socket
08:36:17 : SERVER -> Spawned connection monitor thread.
08:36:17 : CANTO-FETCH -> Started thread for feed CantoFeed: Canto
08:36:17 : FEED -> Fetched previous content for http://codezen.org/canto-ng/feed/.
08:36:17 : CANTO-FETCH -> Started thread for feed CantoFeed: Slashdot
08:36:17 : CANTO-FETCH -> Deferring CantoFeed: Reddit True
08:36:17 : FEED -> Fetched previous content for http://rss.slashdot.org/slashdot/Slashdot.
08:36:17 : CANTO-DAEMON -> Beginning to serve...
08:36:17 : CANTO-DAEMON -> Exiting on exception:
08:36:17 : CANTO-DAEMON -> 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/canto_next/canto_backend.py", line 812, in start
    self.run()
  File "/usr/lib/python3.9/site-packages/canto_next/canto_backend.py", line 573, in run
    self.fetch.reap()
  File "/usr/lib/python3.9/site-packages/canto_next/fetch.py", line 212, in reap
    if not force and thread.isAlive():
  File "/usr/lib/python3.9/site-packages/canto_next/plugins.py", line 125, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'CantoFetchThread' object has no attribute 'isAlive'

08:36:17 : SHELF -> Closing.
08:36:17 : SHELF -> Written tempfile.
08:36:17 : SHELF -> Synced.
08:36:17 : CANTO-DAEMON -> DB shutdown.
08:36:17 : SERVER -> conn (<socket.socket fd=5, family=AddressFamnd.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>, '') from sock <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>
08:36:17 : SERVER -> Spawned new thread.
08:36:17 : CANTO-DAEMON -> Unlocking pidfile.
08:36:17 : CANTO-DAEMON -> Unlocked.
08:36:17 : CANTO-DAEMON -> Exiting cleanly.
```

This was on a clean conf and feeds file (canto-curses was locking up and using 100% cpu on my old conf file).  The canto-log when using my conf file:
```
08:56:51 : CANTO-CURSES -> canto-curses 0.9.9 
08:56:51 : SOCKET -> 

Write:
[
    "VERSION",
    []
]

08:56:51 : SOCKET -> Sent 23 bytes.
08:56:51 : SOCKET -> 

Write:
[
    "WATCHNEWTAGS",
    []
]

08:56:51 : SOCKET -> Sent 28 bytes.
08:56:51 : SOCKET -> 

Write:
[
    "WATCHDELTAGS",
    []
]

08:56:51 : SOCKET -> Sent 28 bytes.
08:56:51 : SOCKET -> 

Write:
[
    "LISTTAGS",
    ""
]

08:56:51 : SOCKET -> Sent 24 bytes.
08:56:51 : SOCKET -> 

Write:
[
    "WATCHCONFIGS",
    ""
]

08:56:51 : SOCKET -> Sent 28 bytes.
08:56:51 : SOCKET -> 

Write:
[
    "CONFIGS",
    []
]

08:56:51 : SOCKET -> Sent 23 bytes.
08:56:51 : SOCKET -> E: 1
08:56:51 : SOCKET -> 

Read:
[
    "VERSION",
    0.9
]
08:56:52 : SOCKET -> E: 17
08:56:52 : SOCKET -> Couldn't get size, interpreting as HUP

08:56:52 : SUBTHREAD -> Thread exiting - disconnected
Any further changes will be forgotten!
08:57:02 : CANTO-CURSES -> Exiting.
```

And the daemon-log (started after feeds information):
```
08:56:51 : CANTO-DAEMON -> Beginning to serve...
08:56:51 : CANTO-DAEMON -> Exiting on exception:
08:56:51 : CANTO-DAEMON -> 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/canto_next/canto_backend.py", line 812, in start
    self.run()
  File "/usr/lib/python3.9/site-packages/canto_next/canto_backend.py", line 573, in run
    self.fetch.reap()
  File "/usr/lib/python3.9/site-packages/canto_next/fetch.py", line 212, in reap
    if not force and thread.isAlive():
  File "/usr/lib/python3.9/site-packages/canto_next/plugins.py", line 125, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'CantoFetchThread' object has no attribute 'isAlive'

08:56:51 : SERVER -> conn (<socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>, '') from sock <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>
08:56:51 : SERVER -> Spawned new thread.
08:56:51 : SERVER -> conn (<socket.socket fd=6, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>, '') from sock <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>
08:56:51 : SERVER -> Spawned new thread.
08:56:51 : SERVER -> conn (<socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>, '') from sock <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/home/mortimer/.config/canto/.canto_socket>
08:56:51 : SERVER -> Spawned new thread.
08:56:51 : SOCKET -> E: 1
08:56:51 : SOCKET -> 

Read:
[
    "VERSION",
    []
]
08:56:51 : SOCKET -> 

Write:
[
    "VERSION",
    0.9
]

08:56:51 : SOCKET -> Sent 24 bytes.
08:56:51 : SOCKET -> E: 1
08:56:51 : SOCKET -> 

Read:
[
    "WATCHNEWTAGS",
    []
]
08:56:51 : SOCKET -> E: 1
08:56:51 : SOCKET -> 

Read:
[
    "WATCHDELTAGS",
    []
]
08:56:51 : SOCKET -> E: 1
08:56:51 : SOCKET -> 

Read:
[
    "LISTTAGS",
    ""
]
08:56:51 : SHELF -> Closing.
08:56:52 : SHELF -> Written tempfile.
08:56:52 : SHELF -> Synced.
08:56:52 : CANTO-DAEMON -> DB shutdown.
08:56:52 : SOCKET -> E: 17
08:56:52 : SOCKET -> No bytes - HUP
08:56:52 : SERVER -> Connection ended.
08:56:52 : SOCKET -> E: 17
08:56:52 : SOCKET -> No bytes - HUP
08:56:52 : SERVER -> Connection ended.
08:56:52 : CANTO-DAEMON -> Unlocking pidfile.
08:56:52 : CANTO-DAEMON -> Unlocked.
08:56:52 : CANTO-DAEMON -> Exiting cleanly.
```

Packages versions (on Arch Linux):
canto-curses = 0.9.9-3
canto-daemon = 0.9.7-4
glibc = 2.32-5
libncursesw.so=6-64 = 6.2-1
libreadline.so=8-64 = 8.0.004-1
python = 3.9.0-1
python-feedparser = 5.2.1-9

**Comment by themoken** [comment]
This is Python 3.9 breakage (I guess I missed the deprecation warnings in 3.8). I've pushed a fix to canto-next so canto-daemon-0.9.8 will include this fix. For now you can build canto-next-git or just wait for the Arch package to update.
