### ISSUE TITLE
Missing Package

### ISSUE THREAD

**Issue by FoundOne** [themoken/canto-curses#57]
`canto-curses` does not work anymore. It fails with 
```
Traceback (most recent call last):
  File "/usr/sbin/canto-curses", line 3, in <module>
    from canto_curses.main import CantoCurses
  File "/usr/lib/python3.13/site-packages/canto_curses/main.py", line 18, in <module>
    from .gui import CantoCursesGui, GraphicalLog
  File "/usr/lib/python3.13/site-packages/canto_curses/gui.py", line 16, in <module>
    from .command import CommandHandler, cmd_execute, register_command, register_alias
  File "/usr/lib/python3.13/site-packages/canto_curses/command.py", line 17, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```
https://docs.python.org/3/library/pipes.html says that it's deprecated.

**Comment by Narrat** [comment]
https://github.com/themoken/canto-curses/blob/master/canto_curses/command.py
Is the module really used? I either missed it or there is just the import of the module? Tried removing it and the curses interface is working again.
